clone_folder: c:\projects\ilastik

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda37-x64


install:
  - cmd: set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: where conda
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda create -q --yes -n %ENV_NAME% -c ilastik-forge -c conda-forge ilastik-dependencies-no-solvers pytest-qt
  # Remove the conda ilastik-meta
  # --force in order not to remove/update anything else
  - cmd: conda remove -n %ENV_NAME% --force ilastik-meta
  - cmd: CALL activate %ENV_NAME%
  - cmd: cd \
  # Get the current master of all submodules
  - cmd: git clone https://github.com/ilastik/ilastik-meta c:\ilastik\ilastik-meta
  - cmd: cd ilastik\ilastik-meta
  - cmd: git submodule update --init --recursive
  - cmd: git submodule foreach "git checkout master"
  - ps: rm -Force -Recurse c:\ilastik\ilastik-meta\ilastik\
  # replace with whatever version of ilastik triggered the appveyor
  - ps: cp -recurse C:\projects\ilastik c:\ilastik\ilastik-meta\ilastik
  # Point to the current ilastik-meta
  - cmd: set ILASTIK_PTH=%MINICONDA%/envs/%ENV_NAME%/Lib/site-packages/ilastik-meta.pth
  - cmd: echo C:/ilastik/ilastik-meta/lazyflow > %ILASTIK_PTH%
  - cmd: echo C:/ilastik/ilastik-meta/volumina >> %ILASTIK_PTH%
  - cmd: echo C:/ilastik/ilastik-meta/ilastik >> %ILASTIK_PTH%

build: off

test_script:
  - cmd: set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: CALL activate %ENV_NAME%
  - cmd: cd \
  - cmd: cd ilastik\ilastik-meta\ilastik\tests
  - cmd: pytest --run-legacy-gui

on_finish:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
