clone_folder: c:\projects\ilastik

environment:
  ENV_NAME: test-env
  # set miniconda version explicitly
  MINICONDA: C:\Miniconda37-x64
  IlASTIK_ROOT: C:\ilastik
  VOLUMINA_SHOW_3D_WIDGET: 0


install:
  - cmd: set "PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: where conda
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda install -c conda-forge conda-build
  # Get the current master of all submodules
  - cmd: git clone https://github.com/ilastik/ilastik-meta %IlASTIK_ROOT%\ilastik-meta
  - cmd: cd %IlASTIK_ROOT%\ilastik-meta
  - cmd: git submodule update --init --recursive
  - cmd: git submodule foreach "git checkout master"
  - ps: rm -Force -Recurse $env:IlASTIK_ROOT\ilastik-meta\ilastik\
  # replace with whatever version of ilastik triggered the appveyor
  - ps: cp -recurse C:\projects\ilastik $env:IlASTIK_ROOT\ilastik-meta\ilastik
  # Point to the current ilastik-meta
  - python ilastik/scripts/devenv.py create -n %ENV_NAME% -c ilastik-forge conda-forge -p ilastik-dependencies-no-solvers

build: off

test_script:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\Scripts;%MINICONDA%\Library\bin;%PATH%
  - cmd: CALL activate %ENV_NAME%
  - cmd: cd %IlASTIK_ROOT%\ilastik-meta\ilastik\tests
  - cmd: set VOLUMINA_SHOW_3D_WIDGET=0
  - cmd: pytest --run-legacy-gui

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
